disabled_rules:
    - function_body_length
    - closing_brace
    - statement_position
    - force_cast
    - force_try
included:
    - Amethyst
    - AmethystTests
line_length:
    warning: 200
    ignores_comments: true
file_length: 500
type_body_length: 400
cyclomatic_complexity: 15
large_tuple: 3
identifier_name:
    excluded:
        - id
